### ISSUE TITLE
Only allow certain statements at the top level

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#110]
Some types of statements should only parse at the top level:

* `namespace`
* `use` namespaces
* `const`
* `__halt_compiler`

In other words, this should not parse, but it currently does:

```php
<?php

if (true) {
    namespace Foo;
}
```

**Comment by ryangjchandler** [comment]
Yeah, we should implement a `top_level_statement()` method and then the regular `statement` method can handle everything else.
