### ISSUE TITLE
Implement all of PHP's operators

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/trunk#19]
https://www.php.net/manual/en/language.operators.precedence.php provides a list of operators ordered by their precedence. We support quite a few of these already but there's some things like bitwise ops and casts that still need to be implemented.

### Unary

* [x] All casts (`(int)`, `(bool)`, etc.)
* [x] Plus (`+`)
* [x] Bitwise not (`~`)
* [x] Prefix decrement (`--$i`)
* [x] Prefix increment (`++$i`)
* [x] Error control (`@`)
* [x] Print (`print`)

### Binary

* [x] Modulo (`%`)
* [x] Left shift (`<<`)
* [x] Right shift (`>>`)
* [x] Bitwise and (`&`)
* [x] Bitwise or (`|`)
* [x] Bitwise xor (`^`)
* [x] Not equal (`<>`)
* [x] Spaceship (`<=>`)
* [x] Logical and (`and`)
* [x] Logical or (`or`)
* [x] Logical xor (`xor`)

### Assignment

* [x] Assign =
* [x] Add assign +=
* [x] Sub assign -=
* [x] Mul assign *=
* [x] Pow assign **=
* [x] Div assign /=
* [x] Concat assign .=
* [x] Mod assign %=
* [x] Bitwise and assign &=
* [x] Bitwise or assign |=
* [x] Bitwise xor assign ^=
* [x] Left shift assign <<=
* [x] Right shift assign >>=
* [x] Null coalesce assign ??=

**Comment by edsrzf** [comment]
Here a list of operators I've found that still need to be implemented:

### Unary

* [ ] Plus (`+`)
* [ ] Bitwise not (`~`)
* [ ] Prefix decrement (`--$i`)
* [ ] Prefix increment (`++$i`)
* [ ] Error control (`@`)
* [ ] Reference (`&`)
* [ ] Print (`print`)

### Binary

* [ ] Modulo (`%`)
* [ ] Left shift (`<<`)
* [ ] Right shift (`>>`)
* [ ] Bitwise and (`&`)
* [ ] Bitwise or (`|`)
* [ ] Bitwise xor (`^`)
* [ ] Not equal (`<>`)
* [ ] Spaceship (`<=>`)
* [ ] Logical and (`and`)
* [ ] Logical or (`or`)
* [ ] Logical xor (`xor`)

**Comment by ryangjchandler** [comment]
Before implementing some of these, the precedence system needs some improvements I think. I'm not a huge fan of the binding power system I've got in place right now and would ideally like to move to a `Precedence` enum and then an `Associativity` enum too.. I think.

**Comment by ryangjchandler** [comment]
@edsrzf Moved your list into the issue description.
