### ISSUE TITLE
Implementation of non-commutative operations between int and float seem broken

### ISSUE THREAD

**Issue by stephanemagnenat** [ryangjchandler/trunk#24]
For example [here](https://github.com/ryangjchandler/trunk/blob/aa2a6c8507f4eba9ccecabdd78a1f95290ffb975/trunk_value/src/sub.rs#L13)

If I'm not mistaken, as sub is non-commutative, the trick to switch `a` and `b` in the match to avoid code duplication leads to an error: the substraction being inverted.

**Comment by ryangjchandler** [comment]
Yeah you're correct. This was missed when I wrote by original code.
