### ISSUE TITLE
Trunk can't handle invalid UTF-8 in PHP source code

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#26]
The Trunk lexer accepts a string and operates on chars. PHP source does not need to be valid UTF-8, and so in degenerate cases can't be represented as a Rust string or as individual chars. In particular, [PHP docs](https://www.php.net/manual/en/language.variables.basics.php) state:

> A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: `^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$`

For instance, you can run this on the CLI:

```sh
$ printf '<?php $var\xff = 1; echo $var\xff . "\n";'|php
1
```

...and it works! This uses the character `\xff` as part of a variable name, which is not otherwise printable and is invalid UTF-8:

```sh
$ printf '<?php $var\xff = 1; echo $var\xff . "\n";'|iconv -f UTF-8
<?php $var
iconv: (stdin):1:10: cannot convert
```

This is admittedly a fairly bizarre corner of the PHP language, but if this toolchain wants to be compatible with the main PHP implementation, it should be fixed.

**Comment by ryangjchandler** [comment]
Yeah I'm guessing the lexer just needs to operator on `u8` values instead and matches need to be updated to use byte literals (`b''`).
