### ISSUE TITLE
Parse readonly properties and classes

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#60]
Readonly properties, which are required to have type declarations:

```php
<?php

class C {
    readonly int $a;
    readonly protected string $b;
    readonly static stdClass $c;

    function __construct(readonly bool $d) {}
}
```

Readonly classes: (coming in PHP 8.2)

```php
<?php

readonly class C {}
```

**Comment by ryangjchandler** [comment]
@edsrzf AFAIK, readonly properties only require the type declaration at compile time / run time. At parse time, they don't need a type declaration (see PHP-Parser behaviour).

**Comment by edsrzf** [comment]
That's true. Is the aim to match behavior with php-parser on this? #23 seems to take the opposite stance.

I've also found a couple other cases where php-parser allows things that Trunk doesn't, but which cause runtime errors anyway, and I'm not sure if I should create issues for them or not.

**Comment by ryangjchandler** [comment]
#23 should be closed. Right now, I want to match PHP-Parser behaviour so that it's consistent when using the library. In the future we might take a different route and tighten up the parsing logic.

**Comment by edsrzf** [comment]
Alright, thanks for clarifying. 👍  I'll file issues for the other inconsistencies I've found.
