### ISSUE TITLE
Parse abstract methods with bodies

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#66]
Abstract methods with bodies cause runtime errors, but are syntactically valid and can be parsed by `nikic/php-parser`. See [this test case](https://github.com/nikic/PHP-Parser/blob/master/test/code/parser/stmt/class/php4Style.test#L8).

**Comment by ryangjchandler** [comment]
This is _weird_.

**Comment by ryangjchandler** [comment]
Going to make a decision on this one and say that we shouldn't support parsing this. Perhaps it's a better idea to not keep our functionality and support inline with `nikic/php-parser` and instead build a better and more robust parser...

Feel free to re-open if you disagree though!

**Comment by edsrzf** [comment]
I think it's a reasonable decision. I can't think of a use case for parsing something that fails immediately, 100% of the time at runtime, as long as it's easy to detect at parse time. And it is.
