### ISSUE TITLE
Parse __halt_compiler

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#71]
[__halt_compiler](https://www.php.net/manual/en/function.halt-compiler.php) is a pseudo-function that stops compilation past the point it's "called". Any arbitrary data can follow and it doesn't need to be valid PHP.

```php
<?php

__halt_compiler();
We can put anything we want here, and it should still parse!
```

**Comment by ryangjchandler** [comment]
This one should be quite easy - it's just a case of converting all tokens after `__halt_compiler()` into a single string and adding that into the statement.

**Comment by edsrzf** [comment]
I don't know if it's that straightforward? The part after `__halt_compiler()` may not even consist of valid PHP tokens.

**Comment by ryangjchandler** [comment]
Ah, yeah you're right. In which case then we emit a `__halt_compiler` token and switch back to `Initial` mode in the lexer.
