### ISSUE TITLE
Parse braced variables

### ISSUE THREAD

**Issue by edsrzf** [ryangjchandler/trunk#77]
These should parse:

```php
<?php
${'a'};
${foo()};
```

**Comment by ryangjchandler** [comment]
Looking at PHP-Parser, it allows any expression inside of the `{}` which makes this a lot simpler.

I think we just need to add:
1. A dedicated token for `$`.
2. Some logic to the expression method to parse out the dynamic variable name.
3. Add a dedicated `DynamicVariable` variant or similar to the `Expression` enum?
